import { db } from './db';
import type {
  Site,
  Material,
  RodEntry,
  LabourWorker,
  AttendanceRecord,
  LabourAdvance,
  SalaryPayment,
  ToolItem,
  TeaSnacksExpense,
  PoojaExpense,
  ElectricityBill,
  WaterBill,
  SiteComment,
  PaymentTransaction,
} from './types';

export async function loadDemoData(): Promise<void> {
  const now = new Date().toISOString();
  const todayStr = now.slice(0, 10);
  const demoSiteId = 'demo-site-sri-murugan';
  const demoUserId = 'user-mistry-velu';

  // Demo Site
  const demoSite: Site = {
    id: demoSiteId,
    userId: demoUserId,
    name: 'Sri Murugan Illam (G+1 Villa)',
    ownerName: 'R. Sundaram',
    ownerPhone: '98401 23456',
    address: 'Plot 42, 3rd Cross Street, Lakshmi Nagar',
    area: 'Tambaram East, Chennai',
    buildingType: 'Residential Villa (G+1)',
    startDate: '2026-01-10',
    expectedCompletionDate: '2026-10-31',
    status: 'Active',
    notes: '2400 sq.ft duplex residential building. Phase: 1st floor roof slab work.',
    isDeleted: false,
    isDemo: true,
    createdAt: now,
    updatedAt: now,
  };

  // Demo Materials
  const demoMaterials: Omit<Material, 'userId'>[] = [
    {
      id: 'demo-mat-1',
      siteId: demoSiteId,
      category: 'sand',
      materialName: 'River Sand (Plastering Quality)',
      supplier: 'Cauvery Sand Traders',
      quantity: 2,
      unit: 'Unit',
      rate: 14500,
      totalAmount: 29000,
      paidAmount: 25000,
      balance: 4000,
      extraPaid: 0,
      purchaseDate: '2026-01-15',
      invoiceNumber: 'INV-CST-881',
      notes: 'Delivered in 2 tipper lorries for foundation & brickwork.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-mat-2',
      siteId: demoSiteId,
      category: 'msand',
      materialName: 'Manufactured Sand (M-Sand Concrete Grade)',
      supplier: 'Sri Balaji Blue Metals',
      quantity: 3,
      unit: 'Unit',
      rate: 9800,
      totalAmount: 29400,
      paidAmount: 29400,
      balance: 0,
      extraPaid: 0,
      purchaseDate: '2026-01-20',
      invoiceNumber: 'INV-SBM-104',
      notes: 'For RCC column concrete mix.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-mat-3',
      siteId: demoSiteId,
      category: 'cement',
      materialName: 'UltraTech Super Cement (PPC)',
      brand: 'UltraTech',
      supplier: 'Rajeshwari Hardware & Cements',
      quantity: 100,
      unit: 'Bags',
      rate: 420,
      totalAmount: 42000,
      paidAmount: 35000,
      balance: 7000,
      extraPaid: 0,
      purchaseDate: '2026-01-25',
      invoiceNumber: 'INV-RHC-390',
      notes: '100 bags stored safely in waterproof shed.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-mat-4',
      siteId: demoSiteId,
      category: 'bricks',
      materialName: 'Chamber Red Wire-Cut Bricks',
      supplier: 'Kanchipuram Brick Kiln',
      quantity: 8000,
      unit: 'Pieces',
      rate: 10.5,
      totalAmount: 84000,
      paidAmount: 70000,
      balance: 14000,
      extraPaid: 0,
      purchaseDate: '2026-02-02',
      invoiceNumber: 'INV-KBK-552',
      notes: '1st quality clay red bricks unloaded at south side.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Rods by diameter
  const demoRods: Omit<RodEntry, 'userId'>[] = [
    {
      id: 'demo-rod-1',
      siteId: demoSiteId,
      diameter: '8 mm',
      brand: 'Tata Tiscon 550D',
      quantityPieces: 50,
      unit: 'kg',
      weightKg: 400,
      ratePerKg: 68,
      totalAmount: 27200,
      paidAmount: 27200,
      balance: 0,
      extraPaid: 0,
      supplier: 'Sri Ram Steels',
      purchaseDate: '2026-01-18',
      invoiceNumber: 'INV-SRS-201',
      notes: 'Used for column stirrups (rings).',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-rod-2',
      siteId: demoSiteId,
      diameter: '12 mm',
      brand: 'Tata Tiscon 550D',
      quantityPieces: 60,
      unit: 'kg',
      weightKg: 850,
      ratePerKg: 68,
      totalAmount: 57800,
      paidAmount: 50000,
      balance: 7800,
      extraPaid: 0,
      supplier: 'Sri Ram Steels',
      purchaseDate: '2026-01-18',
      invoiceNumber: 'INV-SRS-202',
      notes: 'Used for main column reinforcement.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-rod-3',
      siteId: demoSiteId,
      diameter: '16 mm',
      brand: 'JSW Neo TMT',
      quantityPieces: 40,
      unit: 'kg',
      weightKg: 650,
      ratePerKg: 69,
      totalAmount: 44850,
      paidAmount: 40000,
      balance: 4850,
      extraPaid: 0,
      supplier: 'Sri Ram Steels',
      purchaseDate: '2026-01-19',
      invoiceNumber: 'INV-SRS-203',
      notes: 'Plinth beam main bottom bars.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Workers
  const demoWorkers: Omit<LabourWorker, 'userId'>[] = [
    {
      id: 'demo-worker-1',
      siteId: demoSiteId,
      name: 'R. Velu (Head Mistry)',
      phone: '97890 11223',
      category: 'MISTRY',
      dailyWage: 1200,
      joiningDate: '2026-01-10',
      notes: 'Main masonry craftsman and supervisor.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-worker-2',
      siteId: demoSiteId,
      name: 'M. Senthil',
      phone: '94432 33445',
      category: 'PERIYAAL',
      dailyWage: 900,
      joiningDate: '2026-01-10',
      notes: 'Senior mason, brickwork expert.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-worker-3',
      siteId: demoSiteId,
      name: 'K. Lakshmi',
      phone: '96554 55667',
      category: 'SITHAAL',
      dailyWage: 600,
      joiningDate: '2026-01-10',
      notes: 'Mortar helper & brick carrier.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Attendance (Recent 3 days)
  const demoAttendance: Omit<AttendanceRecord, 'userId'>[] = [
    {
      id: 'demo-att-1',
      siteId: demoSiteId,
      workerId: 'demo-worker-1',
      date: todayStr,
      status: 'present',
      dayMultiplier: 1.0,
      notes: 'Full day roof slab alignment',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-att-2',
      siteId: demoSiteId,
      workerId: 'demo-worker-2',
      date: todayStr,
      status: 'present',
      dayMultiplier: 1.0,
      notes: 'Full day brick wall masonry',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-att-3',
      siteId: demoSiteId,
      workerId: 'demo-worker-3',
      date: todayStr,
      status: 'half_day',
      dayMultiplier: 0.5,
      notes: 'Half day afternoon leave',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Labour Advance: explicitly marked Recoverable vs Non-Recoverable
  const demoAdvances: Omit<LabourAdvance, 'userId'>[] = [
    {
      id: 'demo-adv-1',
      siteId: demoSiteId,
      workerId: 'demo-worker-1',
      date: '2026-01-28',
      amount: 2000,
      advanceType: 'Recoverable',
      reason: 'Family festival expenses (Deductible from salary)',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-adv-2',
      siteId: demoSiteId,
      workerId: 'demo-worker-2',
      date: '2026-02-01',
      amount: 1000,
      advanceType: 'Non-Recoverable',
      reason: 'Medical assistance / festival grant (No Return / Non-Recoverable)',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Salary Payments
  const demoSalaryPayments: Omit<SalaryPayment, 'userId'>[] = [
    {
      id: 'demo-sal-1',
      siteId: demoSiteId,
      workerId: 'demo-worker-1',
      date: '2026-02-05',
      daysWorked: 15,
      grossSalary: 18000,
      advanceDeducted: 2000,
      paidAmount: 16000,
      balance: 0,
      extraPaid: 0,
      paymentMode: 'Cash',
      notes: 'Settled for Jan 15-31',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Tools
  const demoTools: Omit<ToolItem, 'userId'>[] = [
    {
      id: 'demo-tool-1',
      siteId: demoSiteId,
      toolName: 'Heavy Concrete Mixer Machine (10/7 CFT)',
      quantity: 1,
      type: 'Rental',
      cost: 4500,
      paidAmount: 4500,
      balance: 0,
      extraPaid: 0,
      purchaseDate: '2026-01-20',
      supplier: 'Annai Equipment Rentals',
      notes: 'Rented for 3 days column pouring.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-tool-2',
      siteId: demoSiteId,
      toolName: 'Stainless Steel Brick Trowel & Leveller',
      quantity: 4,
      type: 'Purchase',
      cost: 1400,
      paidAmount: 1400,
      balance: 0,
      extraPaid: 0,
      purchaseDate: '2026-01-12',
      supplier: 'Standard Tool Works',
      notes: 'New trowels for mistry team.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Tea & Snacks
  const demoTeaSnacks: TeaSnacksExpense[] = [
    {
      id: 'demo-tea-1',
      userId: demoUserId,
      siteId: demoSiteId,
      date: todayStr,
      teaExpense: 120,
      snacksExpense: 180,
      juiceExpense: 150,
      otherFoodExpense: 0,
      totalAmount: 450,
      paidAmount: 450,
      balance: 0,
      extraPaid: 0,
      notes: 'Morning tea + evening samosa & fresh lemon juice for workers.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-tea-2',
      userId: demoUserId,
      siteId: demoSiteId,
      date: '2026-02-10',
      teaExpense: 140,
      snacksExpense: 210,
      juiceExpense: 200,
      otherFoodExpense: 0,
      totalAmount: 550,
      paidAmount: 550,
      balance: 0,
      extraPaid: 0,
      notes: 'Tea, vadai & sugarcane juice during slab work.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Pooja Expense
  const demoPooja: Omit<PoojaExpense, 'userId'>[] = [
    {
      id: 'demo-pooja-1',
      siteId: demoSiteId,
      date: '2026-01-10',
      poojaName: 'Bhoomi Pooja (Foundation Stone Laying)',
      materialsExpense: 3200,
      priestExpense: 2500,
      otherExpense: 800,
      totalAmount: 6500,
      paidAmount: 6500,
      balance: 0,
      extraPaid: 0,
      notes: 'Coconut, flowers, sweets, dakshina to Vadhyar.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Electricity Bill
  const demoElectricity: Omit<ElectricityBill, 'userId'>[] = [
    {
      id: 'demo-elec-1',
      siteId: demoSiteId,
      month: 'January 2026',
      meterNumber: 'TNEB-TEMPORARY-8849',
      billAmount: 1850,
      paidAmount: 1850,
      balance: 0,
      extraPaid: 0,
      dueDate: '2026-02-15',
      notes: 'Temporary construction connection consumption.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Water Bill
  const demoWater: Omit<WaterBill, 'userId'>[] = [
    {
      id: 'demo-water-1',
      siteId: demoSiteId,
      date: '2026-01-22',
      supplier: 'Ganesh Water Tanker Service',
      quantityLoads: '3 Tankers (18,000 Litres)',
      billAmount: 3600,
      paidAmount: 3600,
      balance: 0,
      extraPaid: 0,
      notes: 'Water for curing columns & foundation pit settling.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Comments
  const demoComments: Omit<SiteComment, 'userId'>[] = [
    {
      id: 'demo-comment-1',
      siteId: demoSiteId,
      dateTime: '2026-01-11T10:00:00Z',
      category: 'Inspection',
      commentText: 'Structural engineer inspected foundation soil bearing capacity. Approval granted for column footings.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-comment-2',
      siteId: demoSiteId,
      dateTime: '2026-02-03T16:30:00Z',
      category: 'Client Request',
      commentText: 'Owner requested 6-inch extra lintel height for living room double door.',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Other Expenses
  const demoOtherExpenses = [
    {
      id: 'demo-oth-1',
      siteId: demoSiteId,
      date: '2026-01-14',
      category: 'Transport' as const,
      description: 'Lorry transport for scaffolding steel pipes and centering plates',
      amount: 2500,
      paidAmount: 2500,
      balance: 0,
      extraPaid: 0,
      notes: 'Delivered from central yard to site',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'demo-oth-2',
      siteId: demoSiteId,
      date: '2026-01-21',
      category: 'Fuel' as const,
      description: 'Diesel for concrete mixer and needle vibrator generator (20 Litres)',
      amount: 1960,
      paidAmount: 1960,
      balance: 0,
      extraPaid: 0,
      notes: 'HP petrol bunk fuel receipt #4491',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Demo Payment Transactions
  const demoPayments: PaymentTransaction[] = [
    {
      id: 'PAY-DEMO-001',
      userId: demoUserId,
      siteId: demoSiteId,
      relatedRecordId: 'demo-mat-1',
      module: 'Material',
      date: '2026-01-15',
      amount: 25000,
      paymentType: 'Bank Transfer',
      notes: 'Initial bank NEFT for river sand delivery',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'PAY-DEMO-002',
      userId: demoUserId,
      siteId: demoSiteId,
      relatedRecordId: 'demo-mat-2',
      module: 'Material',
      date: '2026-01-20',
      amount: 29400,
      paymentType: 'UPI',
      notes: 'GPay payment to Sri Balaji Blue Metals',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'PAY-DEMO-003',
      userId: demoUserId,
      siteId: demoSiteId,
      relatedRecordId: 'demo-sal-1',
      module: 'Labour',
      date: '2026-02-05',
      amount: 16000,
      paymentType: 'Cash',
      notes: 'Cash wage disbursement to Velu',
      isDeleted: false,
      isDemo: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Insert all in a transaction
  await db.transaction('rw', [
    db.sites,
    db.materials,
    db.rodEntries,
    db.workers,
    db.attendance,
    db.labourAdvances,
    db.salaryPayments,
    db.tools,
    db.teaSnacksExpenses,
    db.poojaExpenses,
    db.electricityBills,
    db.waterBills,
    db.siteComments,
    db.otherExpenses,
    db.payments,
  ], async () => {
    await db.sites.put(demoSite);
    await db.materials.bulkPut(demoMaterials.map(m => ({ ...m, userId: demoUserId })));
    await db.rodEntries.bulkPut(demoRods.map(r => ({ ...r, userId: demoUserId })));
    await db.workers.bulkPut(demoWorkers.map(w => ({ ...w, userId: demoUserId })));
    await db.attendance.bulkPut(demoAttendance.map(a => ({ ...a, userId: demoUserId })));
    await db.labourAdvances.bulkPut(demoAdvances.map(a => ({ ...a, userId: demoUserId })));
    await db.salaryPayments.bulkPut(demoSalaryPayments.map(s => ({ ...s, userId: demoUserId })));
    await db.tools.bulkPut(demoTools.map(t => ({ ...t, userId: demoUserId })));
    await db.teaSnacksExpenses.bulkPut(demoTeaSnacks.map(t => ({ ...t, userId: demoUserId })));
    await db.poojaExpenses.bulkPut(demoPooja.map(p => ({ ...p, userId: demoUserId })));
    await db.electricityBills.bulkPut(demoElectricity.map(e => ({ ...e, userId: demoUserId })));
    await db.waterBills.bulkPut(demoWater.map(w => ({ ...w, userId: demoUserId })));
    await db.siteComments.bulkPut(demoComments.map(c => ({ ...c, userId: demoUserId })));
    await db.otherExpenses.bulkPut(demoOtherExpenses.map(o => ({ ...o, userId: demoUserId })));
    await db.payments.bulkPut(demoPayments);
  });
}
